### ISSUE TITLE
DatabaseMigrationException after update from EVerest 2024-03 to 2024-05

### ISSUE THREAD

**Issue by lategoodbye** [EVerest/libocpp#661] opened 2024-06-05 14:12 UTC
### OCPP Version

OCPP1.6

### Describe the bug

Today i updated our Tarragon platform from EVerest 2024-03 to 2024-05. The board already had a working OCPP 1.6 setup with Steve. After the update EVerest doesn't start because of DatabaseMigrationException:

````
Jun 05 16:00:58 tarragon manager[4423]: 2024-06-05 16:00:58.862667 [INFO] manager          ::  |  ____\ \    / /               | |
Jun 05 16:00:58 tarragon manager[4423]: 2024-06-05 16:00:58.863035 [INFO] manager          ::  | |__   \ \  / /__ _ __ ___  ___| |_
Jun 05 16:00:58 tarragon manager[4423]: 2024-06-05 16:00:58.863251 [INFO] manager          ::  |  __|   \ \/ / _ \ '__/ _ \/ __| __|
Jun 05 16:00:58 tarragon manager[4423]: 2024-06-05 16:00:58.863448 [INFO] manager          ::  | |____   \  /  __/ | |  __/\__ \ |_
Jun 05 16:00:58 tarragon manager[4423]: 2024-06-05 16:00:58.863616 [INFO] manager          ::  |______|   \/ \___|_|  \___||___/\__|
Jun 05 16:00:58 tarragon manager[4423]: 2024-06-05 16:00:58.863779 [INFO] manager          ::
Jun 05 16:00:58 tarragon manager[4423]: 2024-06-05 16:00:58.863934 [INFO] manager          :: Using MQTT broker localhost:1883
Jun 05 16:00:58 tarragon manager[4424]: 2024-06-05 16:00:58.970839 [INFO] everest_ctrl     :: Launching controller service on port 8849
Jun 05 16:00:59 tarragon manager[4423]: 2024-06-05 16:00:59.013942 [INFO] manager          :: Loading config file at: /etc/everest/config.yaml
Jun 05 16:01:00 tarragon manager[4423]: 2024-06-05 16:01:00.072203 [INFO] manager          :: Config loading completed in 1196ms
Jun 05 16:01:18 tarragon manager[4444]: 2024-06-05 16:01:18.039176 [INFO] energy_manager:  :: Module energy_manager initialized [17334ms]
Jun 05 16:01:18 tarragon manager[4442]: 2024-06-05 16:01:18.211447 [INFO] auth:Auth        :: Module auth initialized [17707ms]
Jun 05 16:01:18 tarragon manager[4451]: 2024-06-05 16:01:18.253900 [INFO] serialcommhub_x  :: Module serialcommhub_x7 initialized [17015ms]
Jun 05 16:01:18 tarragon manager[4450]: 2024-06-05 16:01:18.240353 [INFO] pwmconfig:CbTar  :: chargebyte's Tarragon driver for configuration of digital input reference PWM (version: 0.9.0)
Jun 05 16:01:18 tarragon manager[4450]: 2024-06-05 16:01:18.300490 [INFO] pwmconfig:CbTar  :: Enabled digital input reference PWM 2084000.pwm, channel 0 with period 40000 and duty cycle 20000
Jun 05 16:01:18 tarragon manager[4450]: 2024-06-05 16:01:18.301431 [INFO] pwmconfig:CbTar  :: Module pwmconfig initialized [17206ms]
Jun 05 16:01:18 tarragon manager[4452]: 2024-06-05 16:01:18.353240 [INFO] system:System    :: Module system initialized [17127ms]
Jun 05 16:01:18 tarragon manager[4446]: 2024-06-05 16:01:18.408359 [INFO] grid_connection  :: Module grid_connection_point initialized [17584ms]
Jun 05 16:01:18 tarragon manager[4445]: 2024-06-05 16:01:18.461964 [INFO] evse_security:E  :: Module evse_security initialized [17533ms]
Jun 05 16:01:18 tarragon manager[4449]: 2024-06-05 16:01:18.482898 [INFO] powermeter:Gene  :: Module powermeter initialized [17382ms]
Jun 05 16:01:18 tarragon manager[4454]: 2024-06-05 16:01:18.732166 [INFO] tarragon_pluglo  :: chargebyte's Tarragon driver for plug lock control (version: 0.9.0)
Jun 05 16:01:18 tarragon manager[4455]: 2024-06-05 16:01:18.735539 [INFO] token_provider:  :: Module token_provider initialized [17205ms]
Jun 05 16:01:18 tarragon manager[4454]: 2024-06-05 16:01:18.740211 [INFO] tarragon_pluglo  :: Module tarragon_pluglock initialized [17246ms]
Jun 05 16:01:18 tarragon manager[4453]: 2024-06-05 16:01:18.897755 [INFO] tarragon_bsp:Cb  :: Control Pilot Observation Thread started
Jun 05 16:01:18 tarragon manager[4448]: 2024-06-05 16:01:18.942038 [INFO] ocpp:OCPP        :: OCPP config: /etc/everest/ocpp-config.json
Jun 05 16:01:18 tarragon manager[4448]: 2024-06-05 16:01:18.946014 [INFO] ocpp:OCPP        :: OCPP user config: /var/lib/everest/ocpp16/user-config.json
Jun 05 16:01:18 tarragon manager[4448]: 2024-06-05 16:01:18.958421 [INFO] ocpp:OCPP        :: Augmenting chargepoint config with user_config entries
Jun 05 16:01:18 tarragon manager[4453]: 2024-06-05 16:01:18.977763 [INFO] tarragon_bsp:Cb  :: Primary contactor feedback type: 'nc'
Jun 05 16:01:18 tarragon manager[4453]: 2024-06-05 16:01:18.992562 [INFO] tarragon_bsp:Cb  :: chargebyte's Hardware EVerest Modules (version: 0.9.0)
Jun 05 16:01:18 tarragon manager[4453]: 2024-06-05 16:01:18.994762 [INFO] tarragon_bsp:Cb  :: Module tarragon_bsp initialized [17541ms]
Jun 05 16:01:18 tarragon manager[4453]: 2024-06-05 16:01:18.995721 [INFO] tarragon_bsp:Cb  :: Contactor Handling Thread started
Jun 05 16:01:19 tarragon manager[4448]: 2024-06-05 16:01:19.102703 [INFO] ocpp:OCPP        :: Established connection to database: "/var/lib/everest/ocpp16/lesbos_right.db"
Jun 05 16:01:19 tarragon manager[4448]: 2024-06-05 16:01:19.108227 [INFO] ocpp:OCPP        :: Target version: 2, current version: 0
Jun 05 16:01:19 tarragon manager[4448]: 2024-06-05 16:01:19.112366 [INFO] ocpp:OCPP        :: Migration files to apply:
Jun 05 16:01:19 tarragon manager[4448]: 2024-06-05 16:01:19.122099 [INFO] ocpp:OCPP        :: Migration file [up] version 1, path: /usr/share/everest/modules/OCPP/core_migrations/1_up-initial.sql
Jun 05 16:01:19 tarragon manager[4448]: 2024-06-05 16:01:19.123577 [INFO] ocpp:OCPP        :: Migration file [up] version 2, path: /usr/share/everest/modules/OCPP/core_migrations/2_up-offline-transaction.sql
Jun 05 16:01:19 tarragon manager[4448]: 2024-06-05 16:01:19.141876 [ERRO] ocpp:OCPP       virtual bool ocpp::common::DatabaseConnection::execute_statement(const string&) :: Could not execute statement "PRAGMA foreign_keys = ON;
Jun 05 16:01:19 tarragon manager[4448]: CREATE TABLE CONNECTORS (
Jun 05 16:01:19 tarragon manager[4448]:     ID INT PRIMARY KEY NOT NULL,
Jun 05 16:01:19 tarragon manager[4448]:     AVAILABILITY TEXT
Jun 05 16:01:19 tarragon manager[4448]: );
Jun 05 16:01:19 tarragon manager[4448]: CREATE TABLE AUTH_CACHE (
Jun 05 16:01:19 tarragon manager[4448]:     ID_TAG TEXT PRIMARY KEY NOT NULL,
Jun 05 16:01:19 tarragon manager[4448]:     AUTH_STATUS TEXT NOT NULL,
Jun 05 16:01:19 tarragon manager[4448]:     EXPIRY_DATE TEXT,
Jun 05 16:01:19 tarragon manager[4448]:     PARENT_ID_TAG TEXT
Jun 05 16:01:19 tarragon manager[4448]: );
Jun 05 16:01:19 tarragon manager[4448]: CREATE TABLE AUTH_LIST_VERSION (
Jun 05 16:01:19 tarragon manager[4448]:     ID INT PRIMARY KEY NOT NULL,
Jun 05 16:01:19 tarragon manager[4448]:     VERSION INT
Jun 05 16:01:19 tarragon manager[4448]: );
Jun 05 16:01:19 tarragon manager[4448]: CREATE TABLE AUTH_LIST (
Jun 05 16:01:19 tarragon manager[4448]:     ID_TAG TEXT PRIMARY KEY NOT NULL,
Jun 05 16:01:19 tarragon manager[4448]:     AUTH_STATUS TEXT NOT NULL,
Jun 05 16:01:19 tarragon manager[4448]:     EXPIRY_DATE TEXT,
Jun 05 16:01:19 tarragon manager[4448]:     PARENT_ID_TAG TEXT
Jun 05 16:01:19 tarragon manager[4448]: );
Jun 05 16:01:19 tarragon manager[4448]: CREATE TABLE TRANSACTIONS (
Jun 05 16:01:19 tarragon manager[4448]:     ID INT PRIMARY KEY NOT NULL,
Jun 05 16:01:19 tarragon manager[4448]:     TRANSACTION_ID INT,
Jun 05 16:01:19 tarragon manager[4448]:     CONNECTOR INT NOT NULL,
Jun 05 16:01:19 tarragon manager[4448]:     ID_TAG_START TEXT NOT NULL,
Jun 05 16:01:19 tarragon manager[4448]:     TIME_START TEXT NOT NULL,
Jun 05 16:01:19 tarragon manager[4448]:     METER_START INT NOT NULL,
Jun 05 16:01:19 tarragon manager[4448]:     CSMS_ACK INT NOT NULL,
Jun 05 16:01:19 tarragon manager[4448]:     METER_LAST INT NOT NULL,
Jun 05 16:01:19 tarragon manager[4448]:     METER_LAST_TIME TEXT NOT NULL,
Jun 05 16:01:19 tarragon manager[4448]:     LAST_UPDATE TEXT NOT NULL,
Jun 05 16:01:19 tarragon manager[4448]:     RESERVATION_ID INT,
Jun 05 16:01:19 tarragon manager[4448]:     PARENT_ID_TAG TEXT,
Jun 05 16:01:19 tarragon manager[4448]:     ID_TAG_END TEXT,
Jun 05 16:01:19 tarragon manager[4448]:     TIME_END TEXT,
Jun 05 16:01:19 tarragon manager[4448]:     METER_STOP INT,
Jun 05 16:01:19 tarragon manager[4448]:     STOP_REASON TEXT,
Jun 05 16:01:19 tarragon manager[4448]:     FOREIGN KEY(CONNECTOR) REFERENCES CONNECTORS(ID)
Jun 05 16:01:19 tarragon manager[4448]: );
Jun 05 16:01:19 tarragon manager[4448]: INSERT
Jun 05 16:01:19 tarragon manager[4448]:     OR IGNORE INTO AUTH_LIST_VERSION (ID, VERSION)
Jun 05 16:01:19 tarragon manager[4448]: VALUES (0, 0);
Jun 05 16:01:19 tarragon manager[4448]: CREATE TABLE CHARGING_PROFILES (
Jun 05 16:01:19 tarragon manager[4448]:     ID INT PRIMARY KEY NOT NULL,
Jun 05 16:01:19 tarragon manager[4448]:     CONNECTOR_ID INT NOT NULL,
Jun 05 16:01:19 tarragon manager[4448]:     PROFILE TEXT NOT NULL
Jun 05 16:01:19 tarragon manager[4448]: );
Jun 05 16:01:19 tarragon manager[4448]: CREATE TABLE OCSP_REQUEST (
Jun 05 16:01:19 tarragon manager[4448]:     LAST_UPDATE TEXT PRIMARY KEY NOT NULL
Jun 05 16:01:19 tarragon manager[4448]: );
Jun 05 16:01:19 tarragon manager[4448]: CREATE TABLE TRANSACTION_QUEUE(
Jun 05 16:01:19 tarragon manager[4448]:     UNIQUE_ID TEXT PRIMARY KEY NOT NULL,
Jun 05 16:01:19 tarragon manager[4448]:     MESSAGE TEXT NOT NULL,
Jun 05 16:01:19 tarragon manager[4448]:     MESSAGE_TYPE TEXT NOT NULL,
Jun 05 16:01:19 tarragon manager[4448]:     MESSAGE_ATTEMPTS INT NOT NULL,
Jun 05 16:01:19 tarragon manager[4448]:     MESSAGE_TIMESTAMP TEXT NOT NULL
Jun 05 16:01:19 tarragon manager[4448]: );
Jun 05 16:01:19 tarragon manager[4448]: ": table CONNECTORS already exists
Jun 05 16:01:19 tarragon manager[4448]: 2024-06-05 16:01:19.147456 [ERRO] ocpp:OCPP       bool ocpp::common::DatabaseSchemaUpdater::apply_migration_files(const std::filesystem::__cxx11::path&, uint32_t) :: Could not apply migration file "/usr/share/everest/modules/OCPP/core_migrations/1_up-initial.sql"
Jun 05 16:01:19 tarragon manager[4448]: 2024-06-05 16:01:19.148252 [ERRO] ocpp:OCPP       bool ocpp::common::DatabaseSchemaUpdater::apply_migration_files(const std::filesystem::__cxx11::path&, uint32_t) :: Failure during migration file apply: Database access error
Jun 05 16:01:19 tarragon manager[4448]: 2024-06-05 16:01:19.149341 [INFO] ocpp:OCPP        :: Successfully closed database: "/var/lib/everest/ocpp16/lesbos_right.db"
Jun 05 16:01:19 tarragon manager[4448]: 2024-06-05 16:01:19.150074 [INFO] ocpp:OCPP        :: Database file "/var/lib/everest/ocpp16/lesbos_right.db" is already closed
Jun 05 16:01:19 tarragon manager[4448]: 2024-06-05 16:01:19.338263 [CRIT] ocpp:OCPP       int Everest::ModuleLoader::initialize() :: Caught top level std::exception:
Jun 05 16:01:19 tarragon manager[4448]: Dynamic exception type: ocpp::common::DatabaseMigrationException
Jun 05 16:01:19 tarragon manager[4448]: std::exception::what: SQL migration failed
Jun 05 16:01:19 tarragon manager[4423]: 2024-06-05 16:01:19.437396 [CRIT] manager         int boot(const boost::program_options::variables_map&) :: Module ocpp (pid: 4448) exited with status: 0. Terminating all modules.
Jun 05 16:01:19 tarragon manager[4423]: 2024-06-05 16:01:19.449107 [INFO] manager          :: SIGTERM of child: auth (pid: 4442) succeeded.
Jun 05 16:01:19 tarragon manager[4423]: 2024-06-05 16:01:19.452271 [INFO] manager          :: SIGTERM of child: connector (pid: 4443) succeeded.
Jun 05 16:01:19 tarragon manager[4423]: 2024-06-05 16:01:19.455587 [INFO] manager          :: SIGTERM of child: energy_manager (pid: 4444) succeeded.
Jun 05 16:01:19 tarragon manager[4423]: 2024-06-05 16:01:19.459624 [INFO] manager          :: SIGTERM of child: evse_security (pid: 4445) succeeded.
Jun 05 16:01:19 tarragon manager[4423]: 2024-06-05 16:01:19.479006 [INFO] manager          :: SIGTERM of child: grid_connection_point (pid: 4446) succeeded.
Jun 05 16:01:19 tarragon manager[4423]: 2024-06-05 16:01:19.482230 [INFO] manager          :: SIGTERM of child: hmiled (pid: 4447) succeeded.
Jun 05 16:01:19 tarragon manager[4423]: 2024-06-05 16:01:19.496718 [INFO] manager          :: SIGTERM of child: powermeter (pid: 4449) succeeded.
Jun 05 16:01:19 tarragon manager[4423]: 2024-06-05 16:01:19.506011 [INFO] manager          :: SIGTERM of child: pwmconfig (pid: 4450) succeeded.
Jun 05 16:01:19 tarragon manager[4423]: 2024-06-05 16:01:19.512469 [INFO] manager          :: SIGTERM of child: serialcommhub_x7 (pid: 4451) succeeded.
Jun 05 16:01:19 tarragon manager[4423]: 2024-06-05 16:01:19.518387 [INFO] manager          :: SIGTERM of child: system (pid: 4452) succeeded.
Jun 05 16:01:19 tarragon manager[4423]: 2024-06-05 16:01:19.524702 [INFO] manager          :: SIGTERM of child: tarragon_bsp (pid: 4453) succeeded.
Jun 05 16:01:19 tarragon manager[4423]: 2024-06-05 16:01:19.534188 [INFO] manager          :: SIGTERM of child: tarragon_pluglock (pid: 4454) succeeded.
Jun 05 16:01:19 tarragon manager[4423]: 2024-06-05 16:01:19.546408 [INFO] manager          :: SIGTERM of child: token_provider (pid: 4455) succeeded.
Jun 05 16:01:19 tarragon manager[4423]: 2024-06-05 16:01:19.547495 [CRIT] manager         int boot(const boost::program_options::variables_map&) :: Exiting manager.
Jun 05 16:01:19 tarragon systemd[1]: everest.service: Main process exited, code=exited, status=1/FAILURE
Jun 05 16:01:19 tarragon systemd[1]: everest.service: Killing process 4425 (controller) with signal SIGKILL.
Jun 05 16:01:19 tarragon systemd[1]: everest.service: Failed with result 'exit-code'.
Jun 05 16:01:19 tarragon systemd[1]: everest.service: Scheduled restart job, restart counter is at 14.
````

### To Reproduce

I just updated my board from EVerest 2024-03 to 2024-05.

Please tell if you need further information.

### Anything else?

Current content of the database
````
sqlite> .schema
CREATE TABLE CONNECTORS (
    ID INT PRIMARY KEY NOT NULL,
    AVAILABILITY TEXT
);
CREATE TABLE AUTH_CACHE (
    ID_TAG TEXT PRIMARY KEY NOT NULL,
    AUTH_STATUS TEXT NOT NULL,
    EXPIRY_DATE TEXT,
    PARENT_ID_TAG TEXT
);
CREATE TABLE AUTH_LIST_VERSION (
    ID INT PRIMARY KEY NOT NULL,
    VERSION INT
);
CREATE TABLE AUTH_LIST (
    ID_TAG TEXT PRIMARY KEY NOT NULL,
    AUTH_STATUS TEXT NOT NULL,
    EXPIRY_DATE TEXT,
    PARENT_ID_TAG TEXT
);
CREATE TABLE TRANSACTIONS (
    ID INT PRIMARY KEY NOT NULL,
    TRANSACTION_ID INT,
    CONNECTOR INT NOT NULL,
    ID_TAG_START TEXT NOT NULL,
    TIME_START TEXT NOT NULL,
    METER_START INT NOT NULL,
    CSMS_ACK INT NOT NULL,
    METER_LAST INT NOT NULL,
    METER_LAST_TIME TEXT NOT NULL,
    LAST_UPDATE TEXT NOT NULL,
    RESERVATION_ID INT,
    PARENT_ID_TAG TEXT,
    ID_TAG_END TEXT,
    TIME_END TEXT,
    METER_STOP INT,
    STOP_REASON TEXT,
    FOREIGN KEY(CONNECTOR) REFERENCES CONNECTORS(ID)
);
CREATE TABLE CHARGING_PROFILES (
    ID INT PRIMARY KEY NOT NULL,
    CONNECTOR_ID INT NOT NULL,
    PROFILE TEXT NOT NULL
);
CREATE TABLE OCSP_REQUEST (
    LAST_UPDATE TEXT PRIMARY KEY NOT NULL
);
CREATE TABLE TRANSACTION_QUEUE(
    UNIQUE_ID TEXT PRIMARY KEY NOT NULL,
    MESSAGE TEXT NOT NULL,
    MESSAGE_TYPE TEXT NOT NULL,
    MESSAGE_ATTEMPTS INT NOT NULL,
    MESSAGE_TIMESTAMP TEXT NOT NULL
);
````

**Comment by marcemmers** [comment] 2024-06-07 09:58
Hi @lategoodbye,

This is caused by the fact that we did not have a proper way to update the database schema whenever there are changes. This has been fixed by applying these migration files. Unfortunately the only way to make sure the database is in the correct state is to create a new database and perform all these migrations again. 

This problem should be solved if you delete your database in location `/var/lib/everest/ocpp16/lesbos_right.db`. This should be the last time this is needed. In the future if there are schema changes, the migrations should take care of it.

Let me know if there is still an issue.

**Comment by lategoodbye** [comment] 2024-06-07 15:12
@marcemmers Thanks for the explanation. I renamed the database and EVerest started as expected. I know this is hard to test because with every database version increment the complexity increases. But such issues (EVerest doesn't start) are critical for our customers, because in a lot of cases OCPP is the only connection to the charge point.

**Comment by marcemmers** [comment] 2024-06-07 15:30
@lategoodbye, just to clarify, we are testing any new changes we make to the database version. 

I fully understand that this is a critical part of a charging system and we cannot allow it not to start because of something like this. It was a conscious decision to not allow upgrades from databases created before we had this migration tool since we did not have any control over what was in there, which could have led to a variety of problems down the line.

I will close the issue for now. Please feel free to reopen if you have further comments.

**Closed by marcemmers** 2024-06-07 15:30 UTC
